services:
  zookeeper:
    image: confluentinc/cp-zookeeper:${KAFKA_VERSION}
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:${KAFKA_VERSION}
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "${KAFKA_BROKER_EXTERNAL_PORT}:${KAFKA_BROKER_EXTERNAL_PORT}"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${KAFKA_BROKER_INTERNAL_ADDRESS},PLAINTEXT_HOST://localhost:${KAFKA_BROKER_EXTERNAL_PORT}
      KAFKA_LISTENERS: PLAINTEXT://${KAFKA_BROKER_INTERNAL_ADDRESS},PLAINTEXT_HOST://0.0.0.0:${KAFKA_BROKER_EXTERNAL_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 10
    restart: unless-stopped

  api:
    build: .
    container_name: api_gateway
    command: uvicorn api:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BROKER_INTERNAL_ADDRESS}
      TASK_TOPIC: ${TASK_TOPIC}
    depends_on:
      kafka:
        condition: service_started
    restart: on-failure

  worker:
    build: .
    command: python worker.py
    environment:
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BROKER_INTERNAL_ADDRESS}
      TASK_TOPIC: ${TASK_TOPIC}
      CONSUMER_GROUP_ID: ${CONSUMER_GROUP_ID}
    depends_on:
      kafka:
        condition: service_started
    restart: on-failure

    deploy:
      replicas: 3 
      restart_policy:
        condition: on-failure
    stop_grace_period: 30s
